### ISSUE TITLE
AE瞄具类组件

### ISSUE THREAD

**Issue by qingweiiOS** [axclogo/AxcDrawPath_Tool#2]
AE瞄具类组件 有示例代码么！好好玩啊！

**Comment by WhoJave** [comment]
AE瞄具类组件 有示例代码么！好好玩啊!

**Comment by qingweiiOS** [comment]
> AE瞄具类组件 有示例代码么！好好玩啊!

你学我啊

**Comment by axclogo** [comment]
哈哈哈，就是用那几种绘制图案进行Layer组合，然后独立设置动画即可
示例代码的话在AxcAEUI里边，那个还没完全做好，还没考虑好科技风UI的具体分类和继承关系

**Comment by qingweiiOS** [comment]
好的！炫酷
